# Autogenerated wrapper script for GettextTiny_jll for x86_64-linux-gnu
export msgfmt

using Libiconv_jll
JLLWrappers.@generate_wrapper_header("GettextTiny")
JLLWrappers.@declare_executable_product(msgfmt)
function __init__()
    JLLWrappers.@generate_init_header(Libiconv_jll)
    JLLWrappers.@init_executable_product(
        msgfmt,
        "bin/msgfmt",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
